In [ ]:
import pandas as pd

In [3]:
data = {
    "Image_ID": ["img001.jpg", "img002.jpg", "img003.jpg", "img004.jpg"],
    "Label": ["Fire", "No Fire", "Fire", "No Fire"],
    "Confidence": [0.92, 0.87, 0.95, 0.81],
    "Width": [640, 640, 1280, 1280],
    "Height": [640, 640, 720, 720]
}

df = pd.DataFrame(data)

In [4]:
df

     Image_ID    Label  Confidence  Width  Height
0  img001.jpg     Fire        0.92    640     640
1  img002.jpg  No Fire        0.87    640     640
2  img003.jpg     Fire        0.95   1280     720
3  img004.jpg  No Fire        0.81   1280     720

In [6]:
#how many null values we have
df.isnull().sum()

Image_ID      0
Label         0
Confidence    0
Width         0
Height        0
dtype: int64

In [ ]:
#droping all null values
df.dropna(how = "any")#any row that have null value will be deleted
df.dropna(how = "all")#drop rows if any only if all the values in the row is null

In [ ]:
#filling null values or missing values using fillna()
df.fillna()#inside parentheses provide the value to fill
#i has 2 methofs forward fill and backward fill

In [9]:
df['Image_ID'].replace("img001.jpg" , "new_img")

0       new_img
1    img002.jpg
2    img003.jpg
3    img004.jpg
Name: Image_ID, dtype: object

In [15]:
#dealing with duplicate values
df[df.duplicated(keep = 'first')]#leave first element and choose the other duplicate element

Empty DataFrame
Columns: [Image_ID, Label, Confidence, Width, Height]
Index: []

In [ ]:
#droping duplicates
df = df.drop_duplicates()
#the Whole record gets deleted i.e row